# Generated by Django 4.0.3 on 2022-03-27 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='aoi',
            table='geo_areas_of_interest',
        ),
        migrations.AlterModelTable(
            name='culture',
            table=None,
        ),
        migrations.AlterModelTable(
            name='field',
            table=None,
        ),
        migrations.AlterModelTable(
            name='fitoscan',
            table=None,
        ),
        migrations.AlterModelTable(
            name='research',
            table=None,
        ),
    ]
