# Generated by Django 4.0.3 on 2022-03-27 14:26

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0004_research_bounds_alter_fitoscan_research_soil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='research',
            name='bounds',
        ),
        migrations.AddField(
            model_name='research',
            name='corner1',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='research',
            name='corner2',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
