# Generated by Django 4.0.3 on 2022-04-02 07:14

from django.db import migrations, models
import utils.file_management


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0005_remove_research_bounds_research_corner1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='indexes',
            old_name='ndvi',
            new_name='ndvi_png',
        ),
        migrations.RenameField(
            model_name='indexes',
            old_name='ndwi',
            new_name='ndvi_tiff',
        ),
        migrations.AddField(
            model_name='indexes',
            name='ndwi_png',
            field=models.FileField(default='tt', upload_to=utils.file_management.user_indexes_path),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='indexes',
            name='ndwi_tiff',
            field=models.FileField(default='tt', upload_to=utils.file_management.user_indexes_path),
            preserve_default=False,
        ),
    ]
