# Generated by Django 4.0.3 on 2022-04-02 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0006_rename_ndvi_indexes_ndvi_png_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='research',
            name='corner1',
        ),
        migrations.RemoveField(
            model_name='research',
            name='corner2',
        ),
        migrations.AddField(
            model_name='research',
            name='bounds',
            field=models.JSONField(default={'corner1': {'lat': 54.43, 'lng': 55.55}, 'corner2': {'lat': 54.43, 'lng': 55.55}}),
        ),
    ]
