# Generated by Django 4.0.3 on 2022-05-13 08:31

from django.db import migrations, models
import utils.file_management


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0008_alter_fitoscan_research_alter_indexes_research'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexes',
            name='ndwi_png',
            field=models.FileField(blank=True, upload_to=utils.file_management.user_indexes_path),
        ),
        migrations.AlterField(
            model_name='indexes',
            name='ndwi_tiff',
            field=models.FileField(blank=True, upload_to=utils.file_management.user_indexes_path),
        ),
    ]
